2019-07-12 00:02:59,477 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:02:59,477 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:02:59,535 [django.db.backends:90] [utils:execute] [DEBUG] (0.003) SHOW FULL TABLES; args=None
2019-07-12 00:02:59,539 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-07-12 00:02:59,542 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'zzt'; args=(u'zzt',)
2019-07-12 00:03:04,645 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'admin'; args=('admin',)
2019-07-12 00:03:29,201 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) INSERT INTO `auth_user` (`password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$36000$a15EYoHI1Q90$iH0YeXJ0+340wN7cqszCiVllSLfwH9Ss4mGF8fctfeM=', NULL, 1, 'admin', '', '', 'admin@example.com', 1, 1, '2019-07-11 16:03:29.151000'); args=[u'pbkdf2_sha256$36000$a15EYoHI1Q90$iH0YeXJ0+340wN7cqszCiVllSLfwH9Ss4mGF8fctfeM=', None, True, u'admin', u'', u'', u'admin@example.com', True, True, u'2019-07-11 16:03:29.151000']
2019-07-12 00:05:14,049 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:05:14,051 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:05:14,131 [django.db.backends:90] [utils:execute] [DEBUG] (0.005) SHOW FULL TABLES; args=None
2019-07-12 00:05:14,137 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-07-12 00:06:13,961 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:06:13,961 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:06:13,966 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:06:13.957000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:06:13.957000')
2019-07-12 00:06:13,969 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:06:14,028 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0442EBF0>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x04457CB0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x04409DD0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2019-07-12 00:06:14,032 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0442EBF0>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x04457CB0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x04409DD0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2019-07-12 00:06:14,046 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 1 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(1,)
2019-07-12 00:06:14,049 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/ HTTP/1.1" 200 4174
2019-07-12 00:06:31,144 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:06:31,145 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:06:31,226 [django.db.backends:90] [utils:execute] [DEBUG] (0.005) SHOW FULL TABLES; args=None
2019-07-12 00:06:31,230 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-07-12 00:06:36,605 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:06:36,605 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:06:36,608 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:06:36.602000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:06:36.602000')
2019-07-12 00:06:36,611 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:06:36,651 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x049C0C30>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x049E8D50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0499BE70>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2019-07-12 00:06:36,655 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x049C0C30>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x049E8D50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0499BE70>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2019-07-12 00:06:36,665 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 1 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(1,)
2019-07-12 00:06:36,667 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/ HTTP/1.1" 200 4174
2019-07-12 00:06:46,790 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:06:46,792 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:06:46,795 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:06:46.787000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:06:46.787000')
2019-07-12 00:06:46,796 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:06:46,809 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'post' AND `django_content_type`.`app_label` = 'blog'); args=('post', u'blog')
2019-07-12 00:06:47,002 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category`; args=()
2019-07-12 00:06:47,036 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/category/add/\', u\'name\': \'category\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'category\', \'change_related_template_url\': u\'/admin/blog/category/__fk__/change/\', u\'rendered_widget\': u\'<select name="category" required id="id_category">\\n  <option value="" selected>---------</option>\\n\\n  <option value="1">category test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B19CB0>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:06:47,039 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag`; args=()
2019-07-12 00:06:47,046 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_change_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/tag/add/\', u\'name\': \'tags\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tags" multiple="multiple" id="id_tags">\\n  <option value="1">tag test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B19CD0>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:06:47,046 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/tag/add/\', u\'name\': \'tags\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tags" multiple="multiple" id="id_tags">\\n  <option value="1">tag test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B19CD0>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:06:47,049 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` ORDER BY `auth_user`.`username` ASC; args=()
2019-07-12 00:06:47,059 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/auth/user/add/\', u\'name\': \'author\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'user\', \'change_related_template_url\': u\'/admin/auth/user/__fk__/change/\', u\'rendered_widget\': u\'<select name="author" required id="id_author">\\n  <option value="" selected>---------</option>\\n\\n  <option value="2">admin</option>\\n\\n  <option value="1">zzt</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B19790>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:06:47,069 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/post/add/ HTTP/1.1" 200 9451
2019-07-12 00:06:47,141 [django.db.backends:90] [utils:execute] [DEBUG] (0.003) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:06:47,150 [django.db.backends:90] [utils:execute] [DEBUG] (0.005) SELECT VERSION(); args=None
2019-07-12 00:06:47,187 [django.db.backends:90] [utils:execute] [DEBUG] (0.013) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:06:47.118000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:06:47.118000')
2019-07-12 00:06:47,236 [django.db.backends:90] [utils:execute] [DEBUG] (0.029) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:06:47,279 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:06:48,950 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
2019-07-12 00:06:48,979 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
2019-07-12 00:06:48,983 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20517
2019-07-12 00:06:48,992 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7790
2019-07-12 00:06:48,997 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
2019-07-12 00:06:49,012 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
2019-07-12 00:06:49,157 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
2019-07-12 00:06:49,157 [django.server:124] [basehttp:log_message] [INFO] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
2019-07-12 00:07:10,384 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:10,385 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:10,391 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:10.381000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:10.381000')
2019-07-12 00:07:10,394 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:10,401 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'tag' AND `django_content_type`.`app_label` = 'blog'); args=('tag', u'blog')
2019-07-12 00:07:10,433 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/tag/add/?_to_field=id&_popup=1 HTTP/1.1" 200 2845
2019-07-12 00:07:10,486 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:10,486 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:10,492 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:10.483000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:10.483000')
2019-07-12 00:07:10,493 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:10,496 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:07:35,295 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:35,296 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:35,299 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:35.292000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:35.292000')
2019-07-12 00:07:35,301 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:35,384 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category` WHERE `blog_category`.`id` = 1; args=(1,)
2019-07-12 00:07:35,384 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag` WHERE `blog_tag`.`id` IN (1); args=(1,)
2019-07-12 00:07:35,387 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:35,388 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT (1) AS `a` FROM `blog_category` WHERE `blog_category`.`id` = 1 LIMIT 1; args=(1,)
2019-07-12 00:07:35,390 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT (1) AS `a` FROM `auth_user` WHERE `auth_user`.`id` = 1 LIMIT 1; args=(1,)
2019-07-12 00:07:35,391 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) INSERT INTO `blog_post` (`title`, `body`, `created_time`, `modified_time`, `excerpt`, `category_id`, `author_id`) VALUES ('test455', 'wrfw wrw  wdasxasd', '2019-07-11 16:06:59', '2019-07-11 16:07:01', 'dcsd', 1, 1); args=[u'test455', u'wrfw wrw  wdasxasd', u'2019-07-11 16:06:59', u'2019-07-11 16:07:01', u'dcsd', 1, 1]
2019-07-12 00:07:35,392 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id` FROM `blog_tag` INNER JOIN `blog_post_tags` ON (`blog_tag`.`id` = `blog_post_tags`.`tag_id`) WHERE `blog_post_tags`.`post_id` = 3; args=(3,)
2019-07-12 00:07:35,394 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_post_tags`.`tag_id` FROM `blog_post_tags` WHERE (`blog_post_tags`.`post_id` = 3 AND `blog_post_tags`.`tag_id` IN (1)); args=(3, 1)
2019-07-12 00:07:35,395 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) INSERT INTO `blog_post_tags` (`post_id`, `tag_id`) VALUES (3, 1); args=(3, 1)
2019-07-12 00:07:35,397 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) INSERT INTO `django_admin_log` (`action_time`, `user_id`, `content_type_id`, `object_id`, `object_repr`, `action_flag`, `change_message`) VALUES ('2019-07-11 16:07:35.396000', 1, 8, '3', 'test455', 1, '[{\"added\": {}}]'); args=[u'2019-07-11 16:07:35.396000', 1, 8, u'3', u'test455', 1, '[{"added": {}}]']
2019-07-12 00:07:35,459 [django.server:124] [basehttp:log_message] [INFO] "POST /admin/blog/post/add/ HTTP/1.1" 302 0
2019-07-12 00:07:35,483 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:35,483 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:35,492 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:35.475000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:35.475000')
2019-07-12 00:07:35,496 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:35,503 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT COUNT(*) AS `__count` FROM `blog_post`; args=()
2019-07-12 00:07:35,506 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT COUNT(*) AS `__count` FROM `blog_post`; args=()
2019-07-12 00:07:35,519 [django.db.backends:90] [utils:execute] [DEBUG] (0.003) SELECT `blog_post`.`id`, `blog_post`.`title`, `blog_post`.`body`, `blog_post`.`created_time`, `blog_post`.`modified_time`, `blog_post`.`excerpt`, `blog_post`.`category_id`, `blog_post`.`author_id` FROM `blog_post` ORDER BY `blog_post`.`id` DESC; args=()
2019-07-12 00:07:35,543 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2019-07-12 00:07:35,549 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A48DB0>>}]"
2019-07-12 00:07:35,549 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2019-07-12 00:07:35,572 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:07:35,572 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:07:35,572 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:07:35,576 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/post/ HTTP/1.1" 200 4758
2019-07-12 00:07:35,627 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:35,628 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:35,631 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:35.620000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:35.620000')
2019-07-12 00:07:35,634 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:35,637 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:07:46,371 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:46,371 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:46,375 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:46.367000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:46.367000')
2019-07-12 00:07:46,378 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:46,380 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_post`.`id`, `blog_post`.`title`, `blog_post`.`body`, `blog_post`.`created_time`, `blog_post`.`modified_time`, `blog_post`.`excerpt`, `blog_post`.`category_id`, `blog_post`.`author_id` FROM `blog_post` WHERE `blog_post`.`id` = 1; args=(1,)
2019-07-12 00:07:46,384 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag` INNER JOIN `blog_post_tags` ON (`blog_tag`.`id` = `blog_post_tags`.`tag_id`) WHERE `blog_post_tags`.`post_id` = 1; args=(1,)
2019-07-12 00:07:46,440 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category`; args=()
2019-07-12 00:07:46,447 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/category/add/\', u\'name\': \'category\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'category\', \'change_related_template_url\': u\'/admin/blog/category/__fk__/change/\', u\'rendered_widget\': u\'<select name="category" required id="id_category">\\n  <option value="">---------</option>\\n\\n  <option value="1" selected>category test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04A08FD0>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:46,448 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag`; args=()
2019-07-12 00:07:46,454 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_change_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/tag/add/\', u\'name\': \'tags\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tags" multiple="multiple" id="id_tags">\\n  <option value="1">tag test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04A08750>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:46,456 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/tag/add/\', u\'name\': \'tags\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tags" multiple="multiple" id="id_tags">\\n  <option value="1">tag test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04A08750>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:46,459 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` ORDER BY `auth_user`.`username` ASC; args=()
2019-07-12 00:07:46,467 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/auth/user/add/\', u\'name\': \'author\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'user\', \'change_related_template_url\': u\'/admin/auth/user/__fk__/change/\', u\'rendered_widget\': u\'<select name="author" required id="id_author">\\n  <option value="">---------</option>\\n\\n  <option value="2">admin</option>\\n\\n  <option value="1" selected>zzt</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04A086D0>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:46,473 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/post/1/change/ HTTP/1.1" 200 9772
2019-07-12 00:07:46,509 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:46,510 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:46,515 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:46.506000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:46.506000')
2019-07-12 00:07:46,516 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:46,519 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:07:51,075 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:51,076 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:07:51,079 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:51.073000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:51.073000')
2019-07-12 00:07:51,082 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:51,084 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_post`; args=()
2019-07-12 00:07:51,085 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_post`; args=()
2019-07-12 00:07:51,088 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_post`.`id`, `blog_post`.`title`, `blog_post`.`body`, `blog_post`.`created_time`, `blog_post`.`modified_time`, `blog_post`.`excerpt`, `blog_post`.`category_id`, `blog_post`.`author_id` FROM `blog_post` ORDER BY `blog_post`.`id` DESC; args=()
2019-07-12 00:07:51,105 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2019-07-12 00:07:51,111 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A2AC70>>}]"
2019-07-12 00:07:51,111 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2019-07-12 00:07:51,134 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:07:51,134 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:07:51,134 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:07:51,138 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/post/ HTTP/1.1" 200 4583
2019-07-12 00:07:58,838 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:58,838 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:07:58,842 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:58.836000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:58.836000')
2019-07-12 00:07:58,844 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:58,904 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category`; args=()
2019-07-12 00:07:58,913 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/category/add/\', u\'name\': \'category\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'category\', \'change_related_template_url\': u\'/admin/blog/category/__fk__/change/\', u\'rendered_widget\': u\'<select name="category" required id="id_category">\\n  <option value="" selected>---------</option>\\n\\n  <option value="1">category test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B85D70>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:58,914 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag`; args=()
2019-07-12 00:07:58,921 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_change_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/tag/add/\', u\'name\': \'tags\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tags" multiple="multiple" id="id_tags">\\n  <option value="1">tag test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B85510>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:58,923 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/blog/tag/add/\', u\'name\': \'tags\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tags" multiple="multiple" id="id_tags">\\n  <option value="1">tag test</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B85510>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:58,924 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` ORDER BY `auth_user`.`username` ASC; args=()
2019-07-12 00:07:58,934 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/auth/user/add/\', u\'name\': \'author\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'user\', \'change_related_template_url\': u\'/admin/auth/user/__fk__/change/\', u\'rendered_widget\': u\'<select name="author" required id="id_author">\\n  <option value="" selected>---------</option>\\n\\n  <option value="2">admin</option>\\n\\n  <option value="1">zzt</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x04B85690>, <TextNode: u\'\\n    \'>]>}]'
2019-07-12 00:07:58,940 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/post/add/ HTTP/1.1" 200 9451
2019-07-12 00:07:58,979 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:07:58,980 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:07:58,984 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:07:58.976000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:07:58.976000')
2019-07-12 00:07:58,987 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:07:58,992 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:08:00,657 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:00,657 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:00,661 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:00.654000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:00.654000')
2019-07-12 00:08:00,665 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:00,670 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT COUNT(*) AS `__count` FROM `blog_post`; args=()
2019-07-12 00:08:00,671 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_post`; args=()
2019-07-12 00:08:00,677 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_post`.`id`, `blog_post`.`title`, `blog_post`.`body`, `blog_post`.`created_time`, `blog_post`.`modified_time`, `blog_post`.`excerpt`, `blog_post`.`category_id`, `blog_post`.`author_id` FROM `blog_post` ORDER BY `blog_post`.`id` DESC; args=()
2019-07-12 00:08:00,707 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2019-07-12 00:08:00,713 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A48130>>}]"
2019-07-12 00:08:00,714 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2019-07-12 00:08:00,752 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:00,753 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:00,753 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:00,759 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/post/ HTTP/1.1" 200 4583
2019-07-12 00:08:04,733 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:04,733 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:04,736 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:04.731000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:04.731000')
2019-07-12 00:08:04,740 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:04,756 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A480B0>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x049DFFF0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x04B449F0>, u'request': <WSGIRequest: GET '/admin/blog/'>}, {}, {'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'app_list': [{'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'title': u'Blog administration', 'site_header': u'Django administration', u'LANGUAGE_CODE': 'en-us', 'site_url': '/', 'site_title': u'Django site admin', 'app_label': u'blog', 'has_permission': True, u'LANGUAGE_BIDI': False}]"
2019-07-12 00:08:04,756 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/app_index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A480B0>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x049DFFF0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x04B449F0>, u'request': <WSGIRequest: GET '/admin/blog/'>}, {}, {'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'app_list': [{'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'title': u'Blog administration', 'site_header': u'Django administration', u'LANGUAGE_CODE': 'en-us', 'site_url': '/', 'site_title': u'Django site admin', 'app_label': u'blog', 'has_permission': True, u'LANGUAGE_BIDI': False}]"
2019-07-12 00:08:04,762 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/ HTTP/1.1" 200 2955
2019-07-12 00:08:06,305 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:06,305 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:08:06,309 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:06.302000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:06.302000')
2019-07-12 00:08:06,311 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:06,328 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x04BFF0B0>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x04B46E30>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x04B251F0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2019-07-12 00:08:06,328 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x04BFF0B0>>, 'user': <SimpleLazyObject: <User: zzt>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x04B46E30>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x04B251F0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/category/', 'object_name': 'Category', 'name': u'Categorys', 'add_url': u'/admin/blog/category/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/post/', 'object_name': 'Post', 'name': u'Posts', 'add_url': u'/admin/blog/post/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/blog/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/blog/tag/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2019-07-12 00:08:06,335 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 1 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(1,)
2019-07-12 00:08:06,338 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/ HTTP/1.1" 200 4487
2019-07-12 00:08:08,621 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:08,621 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:08,624 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:08.618000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:08.618000')
2019-07-12 00:08:08,628 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:08,628 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_tag`; args=()
2019-07-12 00:08:08,630 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_tag`; args=()
2019-07-12 00:08:08,632 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag` ORDER BY `blog_tag`.`id` DESC; args=()
2019-07-12 00:08:08,650 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2019-07-12 00:08:08,654 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A48130>>}]"
2019-07-12 00:08:08,654 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2019-07-12 00:08:08,673 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:08,677 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/tag/ HTTP/1.1" 200 4131
2019-07-12 00:08:08,707 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:08,707 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:08:08,710 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:08.703000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:08.703000')
2019-07-12 00:08:08,714 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:08,717 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:08:11,246 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:11,247 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:11,250 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:11.245000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:11.245000')
2019-07-12 00:08:11,253 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:11,256 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag` WHERE `blog_tag`.`id` = 1; args=(1,)
2019-07-12 00:08:11,289 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/tag/1/change/ HTTP/1.1" 200 4016
2019-07-12 00:08:11,315 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:11,316 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:08:11,321 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:11.310000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:11.310000')
2019-07-12 00:08:11,325 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:11,328 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:08:14,197 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:14,197 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:14,200 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:14.194000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:14.194000')
2019-07-12 00:08:14,201 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:14,203 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_tag`; args=()
2019-07-12 00:08:14,204 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT COUNT(*) AS `__count` FROM `blog_tag`; args=()
2019-07-12 00:08:14,210 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag` ORDER BY `blog_tag`.`id` DESC; args=()
2019-07-12 00:08:14,226 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2019-07-12 00:08:14,232 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x04A48970>>}]"
2019-07-12 00:08:14,232 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2019-07-12 00:08:14,249 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:14,253 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/tag/ HTTP/1.1" 200 4131
2019-07-12 00:08:16,282 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:16,282 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:16,286 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:16.279000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:16.279000')
2019-07-12 00:08:16,289 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:16,325 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/tag/add/ HTTP/1.1" 200 3780
2019-07-12 00:08:16,355 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:16,355 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:08:16,359 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:16.350000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:16.350000')
2019-07-12 00:08:16,364 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:16,367 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:08:22,276 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:22,278 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:08:22,280 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:22.274000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:22.274000')
2019-07-12 00:08:22,282 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:22,285 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) INSERT INTO `blog_tag` (`name`) VALUES ('tag 2'); args=[u'tag 2']
2019-07-12 00:08:22,438 [django.db.backends:90] [utils:execute] [DEBUG] (0.153) INSERT INTO `django_admin_log` (`action_time`, `user_id`, `content_type_id`, `object_id`, `object_repr`, `action_flag`, `change_message`) VALUES ('2019-07-11 16:08:22.286000', 1, 9, '2', 'tag 2', 1, '[{\"added\": {}}]'); args=[u'2019-07-11 16:08:22.286000', 1, 9, u'2', u'tag 2', 1, '[{"added": {}}]']
2019-07-12 00:08:22,561 [django.server:124] [basehttp:log_message] [INFO] "POST /admin/blog/tag/add/ HTTP/1.1" 302 0
2019-07-12 00:08:22,588 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:22,589 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:08:22,595 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:22.580000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:22.580000')
2019-07-12 00:08:22,599 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:22,602 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT COUNT(*) AS `__count` FROM `blog_tag`; args=()
2019-07-12 00:08:22,605 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT COUNT(*) AS `__count` FROM `blog_tag`; args=()
2019-07-12 00:08:22,611 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_tag`.`id`, `blog_tag`.`name` FROM `blog_tag` ORDER BY `blog_tag`.`id` DESC; args=()
2019-07-12 00:08:22,637 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2019-07-12 00:08:22,641 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x04BFF270>>}]"
2019-07-12 00:08:22,641 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2019-07-12 00:08:22,661 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:22,661 [django.template:925] [base:_resolve_lookup] [DEBUG] Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "D:\python\python_code\blog_project\venv\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
2019-07-12 00:08:22,667 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/blog/tag/ HTTP/1.1" 200 4518
2019-07-12 00:08:22,701 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:08:22,703 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:08:22,706 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = '3a13cqvhcf0ynuwplxuhhxjhk83zsloz' AND `django_session`.`expire_date` > '2019-07-11 16:08:22.698000'); args=('3a13cqvhcf0ynuwplxuhhxjhk83zsloz', u'2019-07-11 16:08:22.698000')
2019-07-12 00:08:22,709 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:08:22,710 [django.server:124] [basehttp:log_message] [INFO] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
2019-07-12 00:13:27,160 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:13:27,161 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:13:27,230 [django.db.backends:90] [utils:execute] [DEBUG] (0.003) SHOW FULL TABLES; args=None
2019-07-12 00:13:27,236 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-07-12 00:13:32,055 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:13:32,056 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `blog_post`.`id`, `blog_post`.`title`, `blog_post`.`body`, `blog_post`.`created_time`, `blog_post`.`modified_time`, `blog_post`.`excerpt`, `blog_post`.`category_id`, `blog_post`.`author_id` FROM `blog_post` ORDER BY `blog_post`.`created_time` DESC; args=()
2019-07-12 00:13:32,062 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
2019-07-12 00:13:32,062 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category` WHERE `blog_category`.`id` = 1; args=(1,)
2019-07-12 00:13:32,068 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:13:32,072 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category` WHERE `blog_category`.`id` = 1; args=(1,)
2019-07-12 00:13:32,075 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:13:32,078 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT `blog_category`.`id`, `blog_category`.`name` FROM `blog_category` WHERE `blog_category`.`id` = 1; args=(1,)
2019-07-12 00:13:32,082 [django.db.backends:90] [utils:execute] [DEBUG] (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-07-12 00:13:32,085 [django.server:124] [basehttp:log_message] [INFO] "GET / HTTP/1.1" 200 12559
2019-07-12 00:25:26,397 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:25:26,398 [django.db.backends:90] [utils:execute] [DEBUG] (0.000) SELECT VERSION(); args=None
2019-07-12 00:26:20,349 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-07-12 00:26:20,351 [django.db.backends:90] [utils:execute] [DEBUG] (0.001) SELECT VERSION(); args=None
